version: '2'

services:
  nginx:
    build:
      context: ./nginx-container/
      dockerfile: ./nginx-dockerfile
    restart: always
    volumes:
      - ./newapp/build:/app
    ports:
      - 7443:443
      - 7780:80
    links:
      - apiservice

  # webapp: # sufficient to build
  #   build:
  #     context: ./newapp
  #     dockerfile: ./Dockerfile
  #   restart: always
  #   command: ["npm", "start"]
  
  apiservice:
    build:
      context: ./fastapi-container
      dockerfile: ./Dockerfile
    restart: always
    ports: # no port exposure needed; already in same network
      #- "127.0.0.1:8000:80"
      - 8000:80

