version: '2'

services:
  nginx:
    build:
      context: ./nginx-container/
      dockerfile: ./nginx-dockerfile
    restart: no
    volumes: # instead of volume mount copy build directory (better for PROD)
    # TODO: disable write
      - ./newapp/build:/app
    ports:
      - 7443:443
      - 7780:80
    links:
      - apiservice

  apiservice:
    build:
      context: ./fastapi-container
      dockerfile: ./Dockerfile
    restart: no
    # links:
      # - mongodb

#TODO: ADD DEV CONTAINERS HERE; add networks as well...
#RAGHAV BROKE THIS CODe
