version: '2'

services:
  nginx:
    build:
      context: ./nginx-container/
      dockerfile: ./nginx-dockerfile
    restart: always
    ports:
      - 443:443
      - 80:80
    links:
      - webapp

  webapp:
    build:
      context: ./newapp
      dockerfile: ./Dockerfile
    restart: always
    command: ["npm", "start"]
  
  apiservice:
    build:
      context: ./fastapi-container
      dockerfile: ./Dockerfile
    restart: always
    ports: # no port exposure needed; already in same network
      #- "127.0.0.1:8000:80"
      - 8000:80

